# Generated by Django 5.2.12 on 2026-03-26 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(db_index=True, max_length=150)),
                ('manager_name', models.CharField(db_index=True, max_length=150)),
                ('filename', models.CharField(max_length=255)),
                ('date_processed', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration', models.CharField(max_length=50)),
                ('system_processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('candidates_tokens', models.IntegerField(blank=True, null=True)),
                ('cost_thb', models.FloatField(blank=True, null=True)),
                ('overall_score', models.FloatField(default=0.0, help_text='Denormalized QA score')),
            ],
        ),
        migrations.CreateModel(
            name='QACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('call_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_categories', to='qa_dashboard.callreport')),
            ],
        ),
        migrations.CreateModel(
            name='QAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=255)),
                ('criteria', models.TextField()),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10)),
                ('evidence', models.TextField(default='N/A')),
                ('explanation', models.TextField()),
                ('qa_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qa_dashboard.qacategory')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('speaker', models.CharField(db_index=True, max_length=50)),
                ('text', models.TextField()),
                ('emotion', models.CharField(max_length=50)),
                ('language', models.CharField(db_index=True, max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Sequential order of the utterance in the call')),
                ('call_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='qa_dashboard.callreport')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
