# Generated by Django 5.2.12 on 2026-03-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOverviewStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('agents_count', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('category_averages', models.JSONField(default=dict)),
                ('main_emotion', models.CharField(default='N/A', max_length=50)),
                ('emotion_percent', models.FloatField(default=0.0)),
                ('emotion_color', models.CharField(default='var(--neutral)', max_length=50)),
                ('total_cost', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAgentStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('agent_name', models.CharField(db_index=True, max_length=150)),
                ('total_calls', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0.0)),
                ('speaker_distribution', models.JSONField(default=dict)),
                ('language_distribution', models.JSONField(default=dict)),
                ('emotion_distribution', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'agent_name')},
            },
        ),
    ]
