# Generated by Django 5.2.12 on 2026-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_dashboard', '0002_dailyoverviewstat_dailyagentstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='queue',
            field=models.CharField(db_index=True, default='RJI', max_length=50),
        ),
    ]
