# Generated by Django 5.2.12 on 2026-04-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_dashboard', '0003_callreport_queue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyagentstat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyagentstat',
            name='queue',
            field=models.CharField(db_index=True, default='ALL', max_length=50),
        ),
        migrations.AddField(
            model_name='dailyoverviewstat',
            name='queue',
            field=models.CharField(db_index=True, default='ALL', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyoverviewstat',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyagentstat',
            unique_together={('date', 'agent_name', 'queue')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyoverviewstat',
            unique_together={('date', 'queue')},
        ),
    ]
